# Workflow call handles building all the websites using Webpack
name: webpack-build

on:
  workflow_call:
    inputs:
      target:
        description: Target tag or branch to deploy
        type: string
        default: 'main'

jobs:
  webpack_build:
    name: Build Websites
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository (target: ${{ inputs.target }})'
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm ci

      - name: Build Todo List Website
        run: npm run webpack:todolist:build
      
      - name: Build Bookmarker Website
        run: npm run webpack:bookmarker:build
      
      - name: Commit the build
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          message: 'Deploy Webpack Website Builds'
